### ISSUE TITLE
Support .NET 4.5.1

### ISSUE THREAD

**Issue by 01binary** [trichards57/zxcvbn-cs#15]
Hello, I was wondering if you would consider supporting 4.5.1 - I can do the pull request myself, build it on 4.5.1, research the implications, and fix anything that breaks.

Support summary: https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by trichards57** [comment]
Literally the only reason I don't support 4.5.1 is because xunit was being
a pain. I'll have a look at the change note between the two versions and
see what risk there is to just releasing it. Otherwise I'll see if I can
get the testing to work.

**Comment by 01binary** [comment]
According to [XUnit release notes](http://xunit.github.io/releases/2.2), the min version 4.5.1 is only a constraint on Test projects, not the actual code being tested.

I downgraded `zxcvbn-core.csproj` to `net451` leaving `zxcvbn-core-test` at `net452` and the tests for that framework version appear to have passed.

My .NET Core tests crashed through, so I am not sure what's going on there. Probably because I don't have Visual Studio 2017 and executing through .NET Core 2.x instead.

**Comment by trichards57** [comment]
I think I'm seeing the same issue on my machine as well, but the appveyor build seems happy.  I'm going to push a test build and see what happens.
