### ISSUE TITLE
Strong name

### ISSUE THREAD

**Issue by raandree** [trichards57/zxcvbn-cs#18]
Thanks for the work on that project. I would like to use the DLL you have provided on NuGet but I need one with strong name support (https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-sign-an-assembly-with-a-strong-name).

Any chance you can add this to your project and publish a new version to NuGet?

I am trying to use your library in [ManagedPasswordFilter](https://github.com/raandree/ManagedPasswordFilter). As I am calling the .net managed code from C++, the DLL must be signed (at least this is what I have learned). Having all you source code in my project is quite inconvinient.

**Comment by trichards57** [comment]
As Microsoft no-longer recommend Strong Names, I will not be fixing this.

**Comment by trichards57** [comment]
Re-opened this, as I have re-read the MS guidelines and realised that I misread them.

**Comment by trichards57** [comment]
This got fixed by #27
